# Generated by Django 2.1.7 on 2019-05-03 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('confirm_id', models.CharField(max_length=36, verbose_name='ID регистрации')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телеграм ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Телефон')),
                ('connect_token', models.UUIDField(blank=True, help_text='Токен для соединения с Телеграм ботом', verbose_name='Токен для соединения с Телеграм ботом')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
